using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Tradecompanyy
{
    public partial class ShowInfo : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void AddOrder_Click(object sender, EventArgs e)
        {
            OrdersPanel.Visible = true;
        }

        protected void AddNewOrder_Click(object sender, EventArgs e)
        {
            SqlDataSourceOrder.Insert();
            OrderTable.DataBind();
            ProductName.Text = "";
            Price.Text = "";
            Amount.Text = "";
            OrdersPanel.Visible = false;
        }

        protected void CancelOrder_Click(object sender, EventArgs e)
        {
            ProductName.Text = "";
            Price.Text = "";
            Amount.Text = "";
            OrdersPanel.Visible = false;
        }

        protected void EditOrders_Click(object sender, EventArgs e)
        {
            if (EditOrders.Text == "Редактировать заказы")
            {
                OrderTable.AutoGenerateEditButton = true;
                EditOrders.Text = "Закончить редактирование";
            }
            else
            {
                OrderTable.AutoGenerateEditButton = false;
                EditOrders.Text = "Редактировать заказы";
            }
        }

        protected void DeleteOrder_Click(object sender, EventArgs e)
        {
            if (DeleteOrder.Text == "Удалить заказ")
            {
                OrderTable.AutoGenerateDeleteButton = true;
                DeleteOrder.Text = "Закончить удаление";
            }
            else
            {
                OrderTable.AutoGenerateDeleteButton = false;
                DeleteOrder.Text = "Удалить заказ";
            }
        }

        protected void AddCustomer_Click(object sender, EventArgs e)
        {
            PanelCustomer.Visible = true;
        }

        protected void AddNewCustomer_Click(object sender, EventArgs e)
        {
            SqlDataSourceCustomers.Insert();
            CustomersTable.DataBind();
            Name.Text = "";
            Surname.Text = "";
            YearOfBirth.Text = "";
            PanelCustomer.Visible = false;

        }

        protected void CancelAddingCustomer_Click(object sender, EventArgs e)
        {
            Name.Text = "";
            Surname.Text = "";
            YearOfBirth.Text = "";
            PanelCustomer.Visible = false;
        }

        protected void EditCustomers_Click(object sender, EventArgs e)
        {
            if (EditCustomers.Text == "Редактировать покупателей")
            {
                CustomersTable.AutoGenerateEditButton = true;
                EditCustomers.Text = "Закончить редактирование";
            }
            else
            {
                CustomersTable.AutoGenerateEditButton = false;
                EditCustomers.Text = "Редактировать покупателей";
            }
        }

        protected void DeleteCustomer_Click(object sender, EventArgs e)
        {
            if (DeleteCustomer.Text == "Удалить покупателя")
            {
                CustomersTable.AutoGenerateDeleteButton = true;
                DeleteCustomer.Text = "Закончить удаление";
            }
            else
            {
                CustomersTable.AutoGenerateDeleteButton = false;
                DeleteCustomer.Text = "Удалить покупателя";

            }
        }
    }
}